# Generated by Django 5.1.6 on 2025-02-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("condition", models.CharField(max_length=255)),
                ("temperature", models.FloatField()),
                ("humidity", models.IntegerField(blank=True, null=True)),
                ("wind_speed", models.FloatField(blank=True, null=True)),
            ],
            options={
                "unique_together": {("city", "date")},
            },
        ),
    ]
