# Generated by Django 5.1.6 on 2025-02-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="weatherforecast",
            old_name="wind_speed",
            new_name="maxtemp",
        ),
        migrations.RemoveField(
            model_name="weatherforecast",
            name="humidity",
        ),
        migrations.AddField(
            model_name="weatherforecast",
            name="mintemp",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherforecast",
            name="sunrise",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherforecast",
            name="sunset",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherforecast",
            name="totalprec",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
